### ISSUE TITLE
Add example exercises using different mooc-grader view types

### ISSUE THREAD

**Issue by markkuriekkinen** [apluslms/aplus-manual#58]
The example exercises in the manual focus on file upload exercises and questionnaires. There are also other view types in the mooc-grader. There should be some examples of those in the manual too. For example, `view_type` `access.types.stdasync.acceptPost`

https://github.com/apluslms/mooc-grader/tree/master/courses#accesstypesstdasyncacceptpost

RST:

```
.. submit:: newkey 10
  :config: exercises/someexercise/config.yaml
```

config.yaml

```
---
title: Example acceptPost async grading from a text input
view_type: access.types.stdasync.acceptPost
fields:
  - name: answer
    title: Write here
    more: More instructions
    required: true

container:
  image: ...
  mount: exercises/someexercise
  cmd: /exercise/run.sh
```
